### ISSUE TITLE
Documentation on how to use this with a deps.edn project + CIDER

### ISSUE THREAD

**Issue by danielcompton** [clojure-emacs/sayid#46]
I'm looking at trying to use Sayid with a deps.edn project, but I'm not really sure how to translate the requirement of adding `[com.billpiel/sayid "0.0.17"]` to Leiningen's `:plugins` into a deps.edn project. It would be very useful if there was more documentation on this. If I figure it out, I'll make a PR.

**Comment by bbatsov** [comment]
I think the plugin simply adds the nREPL middleware to Lein's middleware vector. The manual setup for `deps.edn` would be to add the dependency and modify `nrepl.edn` or the command-line invocation. This might work out of the box for `cider-jack-in`.
