### ISSUE TITLE
Update install instructions for new versions of CIDER

### ISSUE THREAD

**Issue by danielcompton** [clojure-emacs/sayid#47]
The install instructions say to add a dependency on `[cider/cider-nrepl "0.19.0"]` and `[nrepl/nrepl "0.5.3"]`. New versions of CIDER automatically add the cider-nrepl dependency, and I'm guessing also add unreal as an implicit dependency. Are either/both of these still necessary to install Sayid?

**Comment by bbatsov** [comment]
Nothing's needed if you use `cider-jack-in`. The instructions definitely need some love. I've been meaning to update the landing page for a while now, but I never got to doing so.
