### ISSUE TITLE
Clean up the homepage

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/sayid#49]
The homepage is full of markup that was generated using https://github.com/hniksic/emacs-htmlize. It's extremely hard to work with it, so we should clean up all the excessive markup and inline styles. I think most of the font-locking is non-essential anyways (and the cases where it's useful can be replaced with screenshots).

**Comment by bpiel** [comment]
@AndreaCrotti
FWIW, I put together the site originally. I had reasons for why I did what I did at the time, but I agree with everything Baz said. It makes sense to overhaul to make it significantly easier to work with. 
To answer your question, I doubt that Baz is attached to much, or anything, about the current style. I, obviously, have not made time for sayid in quite a while, so I too would personally appreciate just about anything that anyone contributes.

**Comment by AndreaCrotti** [comment]
Ah thanks @bpiel, well I did a simple export with pandoc

https://github.com/AndreaCrotti/sayid/blob/export-to-markdown/docs/index.md

(which needs a bit of manual cleanup but not so much).
If that plus a style in the github pages styles is enough there isn't really much else to do to get a much nicer format to work with for the website.

**Comment by bpiel** [comment]
@AndreaCrotti 
Nice! I think the only _possibly important_ things you lose here is the styling (especially colors) of the sayid output. This is what I believe Baz was referring to when he mentioned "screenshots". That said, if the conversion artifacts were cleaned up, this seems like a step in the right direction to me. Screenshots can always be added later. Not that my involvement/approval is at all necessary here, just sharing my thoughts.

**Comment by AndreaCrotti** [comment]
Yes sure, in theory I can even take some screenshots of the actual page.
With a theme we'd still get syntax highlighting though, so for the code at least it might not be necessary.

**Comment by bbatsov** [comment]
I'm fine with just having a README. Generally going with AsciiDoc is slightly better as it's easier to generate a nice landing page from it. There's not a lot of documentation, so it's probably fine to keep it only in a README and use screenshots instead of the exported markup.

**Comment by AndreaCrotti** [comment]
Ah yes that's probably better, there isn't enough to split the docs between two places 👍 
but the README should still be markdown right or not?

**Comment by bbatsov** [comment]
I'm fine with both Markdown or AsciiDoc. I use them every day, so it's all the same to me.

**Comment by AndreaCrotti** [comment]
I haven't done the screenshots, but something like this would be fine?
https://github.com/clojure-emacs/sayid/pull/51
For the code blocks we don't need screenshots right?

**Comment by bbatsov** [comment]
Yeah, we don't - just put those examples in fenced code blocks.

**Comment by AndreaCrotti** [comment]
Cool done

**Comment by AndreaCrotti** [comment]
I guess we can close this one now

**Comment by bbatsov** [comment]
Yep. Thanks for moving this one forward!
