### ISSUE TITLE
`sayid-clj-mode-keys` does not return the map it makes

### ISSUE THREAD

**Issue by futuro** [clojure-emacs/sayid#54]
Running `sayid-setup-package` doesn't actually set up the keymaps, and I believe the cause is that `sayid-clj-mode-keys` doesn't return the map it defines, as we see in line 915 of[sayid.el](https://github.com/clojure-emacs/sayid/blob/6febf397d5d610d28100fb1381a82d5e77f0d261/src/el/sayid.el#L915).

I've opened PR #53, which should resolve this issue.

**Comment by bbatsov** [comment]
Fixed by #53.
