### ISSUE TITLE
Very serious bug in the 0.0.19 and the version extract code not work

### ISSUE THREAD

**Issue by zheh12** [clojure-emacs/sayid#57]
https://github.com/clojure-emacs/sayid/commit/cbc3546fb6b1374080f1646ac3a6532a5723b7eb, a quick fix is to use hardcode version.

**Comment by bbatsov** [comment]
Well, that's quite weird as `cider-nrepl` and nREPL use exactly the same code to infer their versions from `project.clj`. I'm quite puzzled as to why isn't this working properly with `sayid`. I don't like the proposed quick-fix much, as I wanted to avoid the possibility to forgot to update the version manually, but if noone comes up with a better idea, that'd be fine by me.

**Comment by Briaoeuidhtns** [comment]
It looks like `cider-nrepl` explicitly includes their `project.clj` file in the jar [here](https://github.com/clojure-emacs/cider-nrepl/blob/3d80096127b6481a18abadb8e45091c3390dc40d/project.clj#L26). I haven't had a chance to test adding that to `sayid`, but it seems like it could be the issue.
