### ISSUE TITLE
nREPL server doesn't start if sayid was not compiled during the current session

### ISSUE THREAD

**Issue by allentiak** [clojure-emacs/sayid#60]
Found in Spacemacs. However, it seems the bug belong here (see detailed report in https://github.com/syl20bnr/spacemacs/issues/13906).

I haven't tried to reproduce it in plain Emacs yet. (Please ping me in case you need me to.)

**Comment by bbatsov** [comment]
I've been using the same approach to infer the package version in other Emacs packages I maintain and this is the first time I hear this doesn't work properly with `use-package`. After all you need to load the file eventually and then the version should be set properly.

**Comment by allentiak** [comment]
Thanks for your feedback, @bbatsov! I have forwarded it to the Spacemacs maintainers. Let's see what happens there...

**Comment by allentiak** [comment]
https://github.com/syl20bnr/spacemacs/issues/13906 has just been closed :-)

**Comment by genmeblog** [comment]
I hit this problem with regular emacs (GNU Emacs 26.3 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2019-09-16) very often :/
What helps is removing sayid.elc file before emacs starts.
