### ISSUE TITLE
sayid-version bug when loading sayid.elc

### ISSUE THREAD

**Issue by cartesian-theatrics** [clojure-emacs/sayid#61]
sayid-version is nil when loading a byte-compiled version of sayid. Spacemacsers ran into this issue here: https://github.com/syl20bnr/spacemacs/issues/13906. There's a workaround, but it would be nice too fix the bug at the source.

**Comment by genmeblog** [comment]
I hit this quite often with regular emacs (GNU Emacs 26.3 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2019-09-16). What helps is removing the `sayid.elc` file.
