### ISSUE TITLE
Support `:as-alias` in `require` (added in Clojure 1.11)

### ISSUE THREAD

**Issue by allentiak** [clojure-emacs/sayid#69]
Example:
```
(require '[company.some-widget.some-entity :as-alias some-entity])
```

`:as-alias` in the Clojure 1.11 Changelog:
https://github.com/clojure/clojure/blob/master/changes.md#22-as-alias-in-require

**Comment by allentiak** [comment]
@bbatsov I added this for `sayid`.
But maybe it should be for `cider`?

**Comment by bbatsov** [comment]
@allentiak You mean the ticket? Yeah, it should probably be for CIDER, although I'm not quite certain what kind of functionality you expect around this.

**Comment by allentiak** [comment]
@bbatsov 
Thanks for the reply!
I will explain my problem in a new ticket for CIDER, then.
